////////////////////////////////////////////////////////////////////////////////////////////////
//Saidas
////////////////////////////////////////////////////////////////////////////////////////////////

                SEL     (comandoAvancaCilindro)
                MEMO    (saidaAvancaCilindro)

                SEL     (comandoRecuaCilindro)
                MEMO    (saidaRecuaCilindro)

                SEL     (comandoLigaMotorEsteira)
                MEMO    (saidaLigaMotorEsteira)

